name: GitHub Actions Test
on:
    push:
        branches:
            - 'master'
jobs:
    Explore-GitHub-Actions:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v2
            - name: Set up your GitHub Actions workflow with a specific version of NodeJS
              uses: actions/setup-node@v2
              with:
                  node-version: 14
                  cache: npm
            - name: Install dependencies
              run: npm ci
            - name: Build
              run: npm run build:lib
            - name: Semantic release
              run: npm run semantic-release
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}
