name: Pull request - Build and test ng-snippets library

on:
    pull_request:
        branches:
            - master
jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v3

            - name: Set up your GitHub Actions workflow with a specific version of NodeJS
              uses: actions/setup-node@v3
              with:
                  node-version: 14
                  cache: npm

            - name: Install dependencies
              run: npm ci

            - name: Build library
              run: npm run build:lib

            - name: Run tests
              run: npm run test:lib-headless
