name: Release - Build and release ng-snippets library

on:
    push:
        branches:
            - master
jobs:
    build-and-semantic-release:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v3

            - name: Set up your GitHub Actions workflow with a specific version of NodeJS
              uses: actions/setup-node@v3
              with:
                  node-version: 14
                  cache: npm

            - name: Install dependencies
              run: npm ci

            - name: Build library
              run: npm run build:lib

            - name: Run tests
              run: npm run test:lib-headless

            - name: Semantic release
              run: npm run semantic-release
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}
